/**
 * WAF Signature Detector
 * Analyzes response headers and HTML bodies to identify firewalls.
 */

const WAF_HEADER_SIGNATURES = [
  { name: 'Cloudflare', headers: ['cf-ray', 'cf-cache-status', 'server'], headerValueMatch: { server: /cloudflare/i } },
  { name: 'AWS WAF / CloudFront', headers: ['x-amz-cf-id', 'x-amz-cf-pop', 'server'], headerValueMatch: { server: /cloudfront/i } },
  { name: 'Akamai', headers: ['x-akamai-transformed', 'akamai-x-cache-on', 'x-true-client-ip'] },
  { name: 'Sucuri', headers: ['x-sucuri-id', 'x-sucuri-cache', 'server'], headerValueMatch: { server: /sucuri/i } },
  { name: 'Imperva Incapsula', headers: ['x-iinfo', 'x-cdn', 'visid_incap'] },
  { name: 'ModSecurity / OWASP CRS', headers: ['x-shared-hosting-source', 'server'], headerValueMatch: { server: /mod_security/i } },
  { name: 'F5 BIG-IP ASM', headers: ['x-wa-info', 'x-cray-site-id'], cookies: ['TS', 'MRHSession'] },
  { name: 'Fastly', headers: ['x-fastly-request-id', 'fastly-rekey'] },
  { name: 'Barracuda', headers: ['barra_counter_session'] }
];

const WAF_HTML_PATTERNS = [
  { name: 'Cloudflare', regex: /attention Required! \| Cloudflare|cloudflare-nginx|Ray ID:/i },
  { name: 'Sucuri', regex: /Access Denied - Sucuri Website Firewall|sucuri cloudproxy/i },
  { name: 'ModSecurity', regex: /ModSecurity|OWASP_CRS|was blocked by ModSecurity/i },
  { name: 'Wordfence', regex: /Generated by Wordfence|wf-blocked|Your access to this site has been limited/i },
  { name: 'Imperva Incapsula', regex: /Incap_Resolv|blocked by Incapsula/i }
];

/**
 * Detect WAF presence
 * @param {Object} headers - Response headers
 * @param {string} html - HTML body content
 * @returns {Object} WAF status
 */
function detectWaf(headers, html) {
  const normHeaders = {};
  if (headers && typeof headers === 'object') {
    for (const [k, v] of Object.entries(headers)) {
      normHeaders[k.toLowerCase()] = String(v);
    }
  }

  // 1. Check headers
  for (const waf of WAF_HEADER_SIGNATURES) {
    // Exact header existence check
    for (const h of waf.headers) {
      if (normHeaders[h]) {
        // Value matching criteria if specified
        if (waf.headerValueMatch && waf.headerValueMatch[h]) {
          if (waf.headerValueMatch[h].test(normHeaders[h])) {
            return { detected: true, name: waf.name, confidence: 'high', source: 'Header Match' };
          }
        } else {
          return { detected: true, name: waf.name, confidence: 'medium', source: 'Header Presence' };
        }
      }
    }

    // Cookie existence check
    if (waf.cookies && normHeaders['set-cookie']) {
      const cookiesStr = normHeaders['set-cookie'];
      for (const cookieName of waf.cookies) {
        if (cookiesStr.includes(cookieName)) {
          return { detected: true, name: waf.name, confidence: 'high', source: 'Cookie Signature' };
        }
      }
    }
  }

  // 2. Check HTML body patterns
  if (html && typeof html === 'string') {
    for (const waf of WAF_HTML_PATTERNS) {
      if (waf.regex.test(html)) {
        return { detected: true, name: waf.name, confidence: 'high', source: 'HTML Pattern' };
      }
    }
  }

  return { detected: false, name: null, confidence: 'low', source: null };
}

module.exports = { detectWaf };
